### ISSUE TITLE
Hotfix fast improvements

### ISSUE THREAD

**Issue by spielhoelle** [devugees/react-shopitme#138]
- Remove `landing/Landing555.css`
- recolor all links that they look beautiful
- createshoppinglist route: just edit one item by a time + fix the bug that Add Item is not getting the edited item
- createshoppinglistedit address edit should contain the data and not as placeholders
- maindeliverypage doesnt contain the notes and the notes fields should be not a textfield
- maindeliverypage currentLocation marker should be different (blue dot)
- scrollUp after selecting a order
- maindeliverypage click on Mapmarker and highlight the order, click on order highlight the Marker
- orderdeliveryhistory: it is possible to delete a pending order by yourself

**Comment by NachoMerino** [comment]
Current progress

- [x] Remove landing/Landing555.css
- [x] recolor all links that they look beautiful
- [ ] createshoppinglist route: just edit one item by a time + fix the bug that Add Item is not getting the edited item
- [x] createshoppinglistedit address edit should contain the data and not as placeholders
- [x] maindeliverypage doesnt contain the notes and the notes fields should be not a textfield
- [x] maindeliverypage currentLocation marker should be different (blue dot)
- [x] scrollUp after selecting a order
- [x] maindeliverypage click on Mapmarker and highlight the order, click on order highlight the Marker (only made half, just one way its ok)
- [ ] orderdeliveryhistory: it is possible to delete a pending order by yourself (wating for the frix from orwa)
