### ISSUE TITLE
Login modal its open when click on the logo

### ISSUE THREAD

**Issue by NachoMerino** [devugees/react-shopitme#186]
When you fresh start the app, if you click in the "logo icon" (shopItMe) nothing happends, and that is perfect, but if you click in another link that suppose to popup the login modal and then close it, the loging modal will popup all the time whee ever you click

How to reproduce it:

1. Enter in App
2. Click on Icon menu (nothing should happend)
3. Click on login/CreateShoppingList/ViewShoppingLists
4. Click back on the icon menu (login modal appear)

Extra Info: will be related with the fix for avoid appear it all the time, when new props came

**Comment by orwa337** [comment]
And if you didn't clicked on login the login modal wouldn't open at all on the "create shopping list" and "main delivery page"
