### ISSUE TITLE
Design Consistency

### ISSUE THREAD

**Issue by Versioncrowd** [devugees/react-shopitme#204]
Rework the CSS so its all looks more consistent

**Comment by NachoMerino** [comment]
write the changes needed , it is so easy to say, but check what changes will be necessary and where

**Comment by Versioncrowd** [comment]
https://docs.google.com/document/d/1oSIDAWvyAQQ0lV_2AbjIUyf9iuJJWStxM8KEK_7UtEk/edit

**Comment by NachoMerino** [comment]
please @Versioncrowd  can you put all the changes into a waffle task?
thank you
